name: Deploy production environment

env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

on:
    pull_request:
        types: [closed]
        branches:
            - main

jobs:
  deploy_production:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel production environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_ACCES_TOKEN }}

      - name: Build with Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_ACCES_TOKEN }}

      - name: Deploy to Vercel production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_ACCES_TOKEN }}